/*
 * scheduler.h
 *
 *  Created on: Mar 19, 2020
 *      Author: yo3bn
 */

#ifndef SRC_KERNEL_INCLUDE_SCHEDULER_H_
#define SRC_KERNEL_INCLUDE_SCHEDULER_H_


/****************************************************************************
 * Name: scheduler
 *
 * Description:
 *    Round Robin task scheduler.
 *
 *    Cycle through all tasks in the task array and change their states
 *    accordingly to the received event parameter.
 *
 *    Do all possible task computation until all tasks are
 *    blocked/waiting/sleeping then return.
 *
 * Input Parameters:
 *    event - Received Kernel Event.
 *
 * Returned Value:
 *    Since there is no other work or event generated by the scheduler, the
 *    return value is zero at the moment.
 *
 * Assumptions:
 *
 ****************************************************************************/

int scheduler(kernel_event_t *event);


#endif /* SRC_KERNEL_INCLUDE_SCHEDULER_H_ */
